version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    command: python satellite_field_monitoring/main.py
    env_file:
      - .env
    volumes:
      - .:/app
